from .general_tools import CHILD_TOOLS as GENERAL_CHILD_TOOLS
from .general_tools import PARENT_TOOLS as GENERAL_PARENT_TOOLS
from .general_tools import TOOL_SPECS as GENERAL_TOOL_SPECS
from .rag_tools import CHILD_TOOLS as RAG_CHILD_TOOLS
from .rag_tools import PARENT_TOOLS as RAG_PARENT_TOOLS
from .rag_tools import TOOL_SPECS as RAG_TOOL_SPECS
from .search_tools import CHILD_TOOLS as SEARCH_CHILD_TOOLS
from .search_tools import PARENT_TOOLS as SEARCH_PARENT_TOOLS
from .search_tools import TOOL_SPECS as SEARCH_TOOL_SPECS

PARENT_TOOLS = GENERAL_PARENT_TOOLS + RAG_PARENT_TOOLS + SEARCH_PARENT_TOOLS
CHILD_TOOLS = GENERAL_CHILD_TOOLS + RAG_CHILD_TOOLS + SEARCH_CHILD_TOOLS
TOOL_SPECS = GENERAL_TOOL_SPECS + RAG_TOOL_SPECS + SEARCH_TOOL_SPECS

__all__ = [
    "PARENT_TOOLS",
    "CHILD_TOOLS",
    "TOOL_SPECS",
    "GENERAL_TOOL_SPECS",
    "RAG_TOOL_SPECS",
    "SEARCH_TOOL_SPECS",
]
